#%RAML 1.0
title: Blog-app types
mediaType: application/json


types: 
  RegisterationRequest:
    type: object
    properties: 
      email: string
      username: string
      password: string
      repeatedPassword: string
  LoginRequest:
    type: object
    properties: 
      username: string
      password: string
    example:
      {
        username: "test",
        password: "test"
      }
    
  JwtTokenResponse:
    type: object
    properties: 
      token: string

  Blog:
    type: object
    properties: 
      id: string
      guid: string
      data: BlogData
      trace: trace
  BlogData:
    type: object
    properties: 
      title: string
      decription: string
  InsertBlogRequest:
    type: object
    properties: 
      title: string
      decription: string
  UpdateBlogRequest:
    type: object
    properties: 
      title: string
      decription: string
  
  Trace:
    type: object
    properties:
      created: Signature
      updated: Signature
  Signature:
    type: object
    properties:
      at:
        description: the datetime format will be in "YYYY-MM-DD HH:MM:SS"
        type: string
        example: "2017-10-31 00:00:00+00:00"
      by: string